package com.microel.trackerbackend.storage.entities.comments.events;

public enum TaskEventType {
    CHANGE_STAGE("CHANGE_STAGE"),
    CREATE_WORK_LOG("CREATE_WORK_LOG"),
    FORCE_CLOSE_WORK_LOG("FORCE_CLOSE_WORK_LOG"),
    CLOSE_WORK_LOG("CLOSE_WORK_LOG"),
    CHANGE_RESPONSIBILITY("CHANGE_RESPONSIBILITY"),
    LINKED_TO_PARENT_TASK("LINKED_TO_PARENT_TASK"),
    UNLINKED_FROM_PARENT_TASK("UNLINKED_FROM_PARENT_TASK"),
    UNLINK_CHILD_TASK("UNLINKED_CHILD_TASK"),
    LINKED_TO_CHILD_TASKS("LINKED_TO_CHILD_TASKS"),
    CHANGE_TAGS("CHANGE_TAGS"),
    CLEAN_TAGS("CLEAN_TAGS"),
    CHANGE_OBSERVERS("CHANGE_OBSERVERS"),
    UNBIND_RESPONSIBLE("UNBIND_RESPONSIBLE"),
    CHANGE_ACTUAL_FROM("CHANGE_ACTUAL_FROM"),
    CHANGE_ACTUAL_TO("CHANGE_ACTUAL_TO"),
    CLEAR_ACTUAL_FROM_TASK("CLEAR_ACTUAL_FROM_TASK"),
    CLEAR_ACTUAL_TO_TASK("CLEAR_ACTUAL_TO_TASK"),
    CLOSE_TASK("CLOSE_TASK"),
    REOPEN_TASK("REOPEN_TASK"),
    EDIT_FIELDS("EDIT_FIELDS"),
    REPORT_CREATED("REPORT_CREATED"),
    MOVED_TO_DIRECTORY("MOVED_TO_DIRECTORY");

    private final String type;

    TaskEventType(String type) {
        this.type = type;
    }

    public String getType() {
        return type;
    }
}
